### ISSUE TITLE
Import source: plugin versions reported incorrectly

### ISSUE THREAD

**Issue by chris-steele** [adapt-security/adapt-authoring-adaptframework#25]
### What happened?
The version installed is 5.31.11 (i.e. APP_DATA/temp/adapt_framework). The version I am importing is 5.31.12. However the tool seems to report the values reversed:

![Image](https://github.com/adapt-security/adapt-authoring-adaptframework/assets/1228225/ea8dea73-23a3-443e-b64d-ad86def7b740)

### Authoring tool version
master

**Comment by taylortom** [comment]
This should be fixed

**Comment by joe-allen-89** [comment]
Fix confirmed, versions showing correctly on import.
