### ISSUE TITLE
Import of latest framework fails on various schema items

### ISSUE THREAD

**Issue by chris-steele** [adapt-security/adapt-authoring-adaptframework#26]
### What happened?
All tool packages using latest code. Adapt framework installed in tool is 5.31.12.

Importing a 5.31.12 source zip file produces following errors:

Import of framework course failed, Import of framework content failed, article a-15 /_assessment/_attempts must be number, ; graphic-component c-25 /_graphic must have required property 'large', /_graphic must have required property 'small', ; graphic-component c-62 /_graphic must have required property 'large', /_graphic must have required property 'small', ; graphic-component c-72 /_graphic must have required property 'large', /_graphic must have required property 'small', ; graphic-component c-95 /_graphic must have required property 'large', /_graphic must have required property 'small', ; graphic-component c-105 /_graphic must have required property 'large', /_graphic must have required property 'small', ; graphic-component c-115 /_graphic must have required property 'large', /_graphic must have required property 'small', ; graphic-component c-125 /_graphic must have required property 'large', /_graphic must have required property 'small', ; graphic-component c-135 /_graphic must have required property 'large', /_graphic must have required property 'small', ; graphic-component c-145 /_graphic must have required property 'large', /_graphic must have required property 'small', 

I expect these issues should be resolved in the framework (i.e. https://github.com/adaptlearning/adapt_framework/tree/master/src/course/en)

### Steps to reproduce
See above

### Authoring tool version
master

**Comment by taylortom** [comment]
Fixed

**Comment by joe-allen-89** [comment]
Confirm fix, no schema errors on import.
