### ISSUE TITLE
Update adapt-cli dependency

### ISSUE THREAD

**Issue by chris-steele** [adapt-security/adapt-authoring-adaptframework#59]
### What happened?

Require adapt-cli v3.1.5 to prevent runtime error for plugins not bower-registered. See https://github.com/adaptlearning/adapt-cli/pull/204

### Steps to reproduce

Occurs when importing course using plugins that are not bower-registered

### Authoring tool version

Any

**Comment by taylortom** [comment]
Fixed in https://github.com/adapt-security/adapt-authoring-adaptframework/pull/58
